services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: ["${POSTGRES_PORT}:5432"]

  redis:
    image: redis:7
    command: ["--appendonly","yes"]
    ports: ["${REDIS_PORT}:6379"]

  web:
    image: <Docker Hub username>/cutly:v1
    build: .
    ports: ["${WEB_PORT}:5000"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT_INTERNAL}
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on: [postgres, redis]