apiVersion: v1
kind: ConfigMap
metadata:
  name: cutly-config
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "cutly"
  DB_USER: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
