apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cutly
  template:
    metadata:
      labels:
        app: cutly
    spec:
      containers:
        - name: web
          image: cosmic09/cutly:v1
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: cutly-config
            - secretRef:
                name: cutly-secrets
          readinessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
